pubName: reading_shelf_api_client
pubVersion: 1.0.0
pubDescription: Generated Dio client for the Reading Shelf sample API.
sourceFolder: src
serializationLibrary: built_value
enumUnknownDefaultCase: true
useOptional: true
